service: seams

provider:
  name: aws
  runtime: nodejs12.x
  deploymentBucket:
    name: lambdas-deploys
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DeleteItem
        - dynamodb:GetItem
        - dynamodb:Scan
        - dynamodb:PutItem
      Resource:
        Fn::GetAtt:
          - ConnectionsTable
          - Arn
  environment:
    APIG_ENDPOINT:
      Fn::Join:
      - ''
      - - Ref: WebsocketsApi
        - .execute-api.
        - Ref: AWS::Region
        - '.amazonaws.com/'
        - ${self:custom.stage}
    CONNECTIONS_TABLE:
      Ref: ConnectionsTable

custom:
  stage: ${opt:stage, 'dev'}

functions:
  web:
    handler: src/web.handler
    events:
      - http:
          path: /
          method: GET
  websocket:
    handler: src/websocket.handler
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $default
      - websocket:
          route: $disconnect
plugins:
  - serverless-offline

resources:
  Resources:
    ConnectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: "socket_connections"
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        SSESpecification:
          SSEEnabled: true
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true